# Generated by Django 4.2.20 on 2025-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pokemon_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprites',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
