# Generated by Django 4.2.20 on 2025-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pokemon_abilities_pokemon_base_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='sprites',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='stats',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='products.ability'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(blank=True, to='products.type'),
        ),
    ]
