# Generated by Django 4.2.20 on 2025-03-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_pokemon_stats_pokemon_attack_pokemon_defense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
